### ISSUE TITLE
[FEEDBACK] NA Exynos test build

### ISSUE THREAD

**Issue by fakemanoan** [fakemanoan/LineageOS-Releases#106]
This is a feedback page for those using the test Lineage 18.1 builds for the NA exynos variants of the S6, S6 edge and Note 5.
You can download the builds here: https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A11PRE-NAEXYNOSJAN25

There is no special TWRP requirement. There is an included recovery in the zip that you can flash also, and it should work, though it is only Lineage recovery, and is fairly limited. 

Please upload logcats here. I am interested particularly when you are in a call with someone

If you need assistance in capturing a logcat, look here: https://fakemanoan.github.io/logcat
This is to enable SELinux enforcing on a unified build. If no one provides logs, then I will simply not build for these devices anymore as it is too intensive for me to maintain. 

Any other feedback is welcomed.

**Comment by petquipue** [comment]
Is it ok to get the log using 9.1-20240513-UNOFFICIAL-zerofltecan-2.zip  ?

**Comment by fakemanoan** [comment]
> Is it ok to get the log using 9.1-20240513-UNOFFICIAL-zerofltecan-2.zip ?
sure

**Comment by opsNote5** [comment]
Hi @fakemanoan 

I'd like to give you an update where I am at, and my findings so far.
This is my first time to flash / use custom ROM, so please let me know if you / anyone feel missing info.

My configuration
- SM-N90W8
- Official TWRP 3.4.0-0 Recovery
- No Google Apps yet (I may flash ROM later again in some point)

What is working/tested:
- Boot, home screen (launcher)
- Cellular data, WiFi (without captive portal) connectivity
- VPN
- Audio
- Apps (such as Setting, Default Browser, F-Droid, NewPipe, Tailscale)

Non-critical issues I have noticed/faced:
- TWRP install signature failure (I was wondering my zip was wrong or not, and spend sometime to download / reinstall the firmware)
- Setting > About phone > Model - it says SM-N920C instead of SM-N920W8

Critical issue (so far):
- Unable to connect Public WiFi with Captive portal.

I do not know it is related to 'SELinux', but you can probably tell so I am reporting it.

I am sending zip via xdaforum message / conversation.
Two log files in the zip, both log should have start booting up system, and connect WiFi.
One is working sample (Without CaptivePortal), the other non-working (With CaptivePortal)
The password will be sent via message.

**Comment by fakemanoan** [comment]
Thanks. I can already see a few denials that will be easy to fix. 

Any problems with in-call audio specifically?

I will release an updated build with some new SEPolicies in a few days. Hopefully that will fix some issues

**Comment by opsNote5** [comment]
Hi @fakemanoan 

Update:
- I have reported CaptivePortal previously, later I have found that some other WiFi site allow me to connect their Internet.. (so the issue may be not CaptivePortal, and it may be more of WiFi / specific network I was connecting. I'm not sure)
- I have tested Text message (includes MMS), and both sending and receiving are working fine.
- Not working: VoiceCall:
  - Connection is made successfully, but voice is not delivered to the other end
  - This happens for both call-in / call-out
  - After the phone line is connected, the voice from this device cannot be heard on the other end, and vice verse.

I saw briefly 
https://xdaforums.com/t/research-wip-possible-volte-enablement-for-samsung-devices-on-aosp-based-roms.4664947/ thread. Is that something we are concerned and testing about?

I have made another log zip file (log-voice-call.zip) and sent to you like before.
I don't know whether call out / in matters for you or not, so I made both log files.

The voice-call is not primal feature I use, so it took me a bit to swap SIM and tested it out. Sorry to wait you.

**Comment by fakemanoan** [comment]
Thanks for the test logs.

The Canadian/T-mobile variants of these devices have an Audio EarSmart IC that is used for call audio, so has the potential to introduce issues. The VoLTE fix you linked is not stable and does not work on every samsung device at this time.  Since VoLTE isnt available, you are calling via 2G.

It is interesting that call audio at this time does not work, as I applied the previous fixes that were confirmed working. 
https://github.com/fakemanoan/LineageOS-Releases/issues/92#issuecomment-2207501994

I will come up with a fix which should hopefully fix the issue.

**Comment by WeakFray** [comment]
Hey @fakemanoan, I've flashed the 18.1 test build to my S6 edge and I've gotten around to testing it today.

Phone details:
- S6 edge (SM-G925W8)
- Build: `lineage-18.1-20250106-UNOFFICIAL-zeroltecan`
- No Google apps installed

Tested and working:
- Startup
- Mobile data
- Wi-Fi (one exception, see below)
- Bluetooth (calls and media)
- Audio
- Calls (incoming/outgoing, audio works)
- Other applications

Non-critical issues:
- During an outgoing call, it takes a few seconds for the in-call buttons (mute, keypad, etc.) to become available (not grayed out) after the called party answers

Critical issues:
- Some Wi-Fi networks fail to connect

The phone fails to connect to certain Wi-Fi networks like my main router. However, it connects to my Wi-Fi extender just fine. I've only seen this behavior with my main router though, not other networks, so I'm not sure if this is related to SELinux policies, but I'll include the logcat just in case.

I also find it weird that call audio is working on my S6 edge, but not the Note 5.

One logcat was made during a phone call, and the other was the previously mentioned Wi-Fi issue. I'll keep testing this build whenever I have free time. If there's anything else you need me to test, let me know. Thank you for your hard work developing for these devices!

[logcat_20250118_1745_Call.txt](https://github.com/user-attachments/files/18467179/logcat_20250118_1745_Call.txt)
[logcat_20250118_1751_Wi-Fi.txt](https://github.com/user-attachments/files/18467180/logcat_20250118_1751_Wi-Fi.txt)

**Comment by opsNote5** [comment]
Hi @fakemanoan and @WeakFray 

I would like to share (possibly important) information about my phone's baseband version.
This was my first time flashing the firmware, so I didn't know anything, but more reading, I feel it is related.
My initial thought was that once phone get new firmware, everything (includes how phone communicate to cell tower)I get updated. Correct me, but this was probably wrong assumption.
Before flashing the firmware, I had baseband version 'N920W8VLU2BPE3, see screenshot I took while I was in 'stock' ROM.
![Image](https://github.com/user-attachments/assets/80b66a8d-5cfd-4e01-be54-2d7b166818aa)
This was quite old and the latest version: https://samfw.com/firmware/SM-N920W8/FMC/N920W8VLU2BPE3
After I installed lineageOS. I was still seeing the same baseband version.

I can find much newer one  N920W8VLU6CVG1 (Build date is 2022-07-21)

I do have another problem, which I also want to resolve too. Currently (and before installing LineageOS), the phone doesn't connect to 'Rogers' network (one of the most popular carrier in Canada, and I would like to use too) in 4G, and only able to connect 3G (which will be discontinue soon).

So my thought is that this is something I want to resolve my-side,
I will install stock Samsung firmware using Odin3
https://www.sammobile.com/samsung/galaxy-note-5/firmware/SM-N920W8/XAC/download/N920W8VLU6CVG1/1671262/  
Once installed (and probably quick tested), re-do TWRP, and install LineageOs again.

Is that something reasonable, and I want to try? Can you please advice me.
Then I can try re flashing everything and can report back.

**Comment by fakemanoan** [comment]
@WeakFray 
Thanks for the logs. I can see some denials regarding earsmart during the call, they will be addressed in an upcoming version.

Regarding your wifi issues, is your wifi network WPA3? 

@opsNote5 
It is advised you update to the latest firmware before you flash. That may explain why call audio works for some but not others.

You can try that firmware. nothing bad should happen.

**Comment by opsNote5** [comment]
I will try with new 'baseband' version. I will update here once I have done.

**Comment by WeakFray** [comment]
Hey @fakemanoan. 
> Regarding your wifi issues, is your wifi network WPA3?

My Wi-Fi network uses both WPA2 and WPA3 at the same time. I initially thought this wouldn't be an issue as my S6 edge didn't have any problems connecting to it when it was running the stock ROM. Whenever I try to connect to it, a toast message appears after a few seconds: `Failed to connect to network`.

I've mentioned before that my Wi-Fi extender connects fine with the S6 edge. The extender only supports WPA2, so I'll try switching the Wi-Fi security on my main router to WPA2 later and see if that fixes the issue.

**Comment by 514coder** [comment]
> > Is it ok to get the log using 9.1-20240513-UNOFFICIAL-zerofltecan-2.zip ?
> 
> sure

Sorry for the delay, I only have access to the phone once a week. The G920W8 gave me an Acces Denied error when trying to get the logcat. Do I need to root the phone? Also is it still needed since you got some log files from other users?

**Comment by petquipue** [comment]
> > Is it ok to get the log using 9.1-20240513-UNOFFICIAL-zerofltecan-2.zip ?
> 
> sure

Sorry for the delay, I only have access to the phone once a week. The G920W8 gave me an Acces Denied error when trying to get the logcat. Do I need to root the phone? Also is it still needed since you got some log files from other users?

**Comment by opsNote5** [comment]
@fakemanoan 

I have flashed stock ROM N920W8VLU6CVG1.
Then re-flash TWRP 3.4.0-0/lineage-18.1-20250106-UNOFFICIAL-nobleltetmo.zip 

So the new baseband version allow me to connect LTE/4G network in both Rogers and FreedomMobile network, which is great improvement to me.

Re: Phone call / audio issue, this is still not resolved.
What I confirmed is that
1. With Stock Rom N920W8VLU6CVG1, the call-out/call-in audio both are working. (Freedom Mobile network) - It may be connected via VoLTE. (I didn't test if I force to use 3G, what happens)
2. After lineage-18.1-20250106-UNOFFICIAL-nobleltetmo.zip is installed,  and using Freedom Mobile network:
2,1. While connecting to 4G network, and if I make a call, I can see phone switch from 4G to 3G (HSPA+), and the connection is made successfully (can see length of line connected) but, the receive/send audio has problem, like before. (i.e. I don't hear anything, they don't hear anything) 
2.2. While connecting to 3G network (PreferredNetworkType=3G, H+ sign in the top), the connection is made successfully (can see length of like connected) like above, and receive/send audio is not working. (i.e. I don't hear anything, they don't hear anything) 

Since I didn't see any improvement re: calling audio, I didn't make log files, but If it is needed, please let me know.

**Comment by fakemanoan** [comment]
> > > Is it ok to get the log using 9.1-20240513-UNOFFICIAL-zerofltecan-2.zip ?
> > 
> > 
> > sure
> 
> Sorry for the delay, I only have access to the phone once a week. The G920W8 gave me an Acces Denied error when trying to get the logcat. Do I need to root the phone? Also is it still needed since you got some log files from other users?

@petquipue Sorry for the delayed response. All you need to do is enable adb debugging in developer options, and it should work. 


> 
> Since I didn't see any improvement re: calling audio, I didn't make log files, but If it is needed, please let me know.

@opsNote5 I will look into this a bit more later. I will release a new build shortly.

**Comment by fakemanoan** [comment]
https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A11-11022025 there are new releases please test to see if your issues are resolved

@WeakFray @opsNote5 

any additional logs are appreciated

**Comment by opsNote5** [comment]
@fakemanoan 

Environment: Model: SM-N920W8	
Recovery: TWRP-3.4.0-0 recovery	
	
Firmware installed:
- lineage-18.1-20250211-UNOFFICIAL-nobleltetmo.zip 
- No GApps
- The data partition was NOT flashed (i.e. continue form the last build)
	
	
Working
- Boot
- General Apps functionality (include Built-in Browser, F-Droid, NewPipe, Tailscale, Fennec (firefox clone), includes audio playback)
- Bluetooth (Headphone)
- Many WiFi (but few not working)
- Cellular network - Data Connection (basic level working)
	
Not working (the same / similar to previously reported, I didn't see any improvement, in this area)
- WiFi connection - Unable to connect to certain WiFi
- Call-in/out audio (unable to hear, after the connection has been made)

For those not working, I have sent you log file like before.

**Comment by WeakFray** [comment]
Hey @fakemanoan, I've started testing the new release you've built. I've done a clean flash since I wanted to install Google apps.

Phone details:

- S6 edge (SM-G925W8)
- Build: `lineage-18.1-20250211-UNOFFICIAL-zeroltecan`
- Google apps installed: `MindTheGapps`
- ROM was clean flashed

Tested and working:

- Startup
- Mobile data
- Wi-Fi
- Bluetooth (media)
- Audio
- GPS
- Calls (incoming/outgoing, audio works as usual)
- Other apps

Non-critical issues:

- The phone takes a while to start ringing when someone dials it. It usually varies from 5 to 15 seconds. However, the mobile data switches from 4G to H+ almost immediately after dialling the phone. In one instance, the phone didn't ring at all even after the mobile data connection switched, so I've attached that logcat here just in case.

Critical issues:

- **Call audio through Bluetooth no longer works properly.** On my end, I hear nothing from the other party, and the other party hears a constant garbled sound. This stops when the audio output is set to either the speaker or the earpiece, and call audio then works like normal. This only happens whenever a Bluetooth device is selected for audio output. If I remember correctly, this wasn't an issue in the last build.
- **WPA3 networks fail to connect.** I was able to confirm that the phone fails to connect to Wi-Fi networks that use dual WPA2/WPA3 security. The phone doesn't detect pure WPA3 networks, but I think that is to be expected.

Logcats:

- Call (without Bluetooth): [logcat_20250217_1848_Call-Normal.txt](https://github.com/user-attachments/files/18838533/logcat_20250217_1848_Call-Normal.txt)
- Call (with Bluetooth): [logcat_20250217_1829_Call-BT.txt](https://github.com/user-attachments/files/18838532/logcat_20250217_1829_Call-BT.txt)
- Failed call (phone didn't ring): [logcat_20250217_1845_Call-Normal-Fail.txt](https://github.com/user-attachments/files/18838534/logcat_20250217_1845_Call-Normal-Fail.txt)
- Wi-Fi: [logcat_20250217_1853_Wi-Fi.txt](https://github.com/user-attachments/files/18838531/logcat_20250217_1853_Wi-Fi.txt)

**Comment by petquipue** [comment]
Can't provide log right now since I don't have my g920w8 (lend it to someone) but latest 18.1 yesterday release have no sound during call. Otherwise mic and speaker seem to work well in other apps.

**Comment by opsNote5** [comment]
@fakemanoan I was unable to install the firmware (lineage-18.1-20250408-UNOFFICIAL-noblelte.zip) to my SM-N920W8 initially.
I used to use TWRP3.4.0, and it was successful earlier zip, but NOT for this 20250408, the installation didn't work.

Here was the error
=====
TWRP generates an error message
Here is the message I got: (I've used screencapture tool, so it may contain small typo) 
Installing zip file '/sdcard/Download/lineage-18.1-20250408-UNOFFICIAL-nobleIte.zip'
Checking for Digest file.
Unmounting System..
E3004: This package is for device: noblelte,
nobleltedd, nobleltedv,nobleltejv,nobleltektt,
nobleltelgt,noblelteskt,nobleltetmo,nobleltebmc:
this device is nobleltecan
Vpdater process ended with ERROR: 1
Error installing zip file '/sdcard/Download/lineage-
18.1-20250408-UNOFFICIAL-noblelte.zip'
Updating partition details...
...done
=====

I did unzip the file and modified 2 files by hand
- \META-INF\com\android\metadata
- \META-INF\com\google\android\updater-script"
(add: nobleltecan)
and made zip file, and I was able to install the zip. and the system booted up successfully

I have not fully tested the new firmware yet, but I have briefly confirmed the audio call worked. That is awesome and thank you.
I will do further testing later, probably upcoming weekend, and update you / here.

**Comment by fakemanoan** [comment]
Thanks for testing. I really need to release my own twrp for the note 5, as nobleltecan is a made-up codename and one of the main reasons for doing this is removing jank like that.

Strange that S6 models have seemingly lost call audio? Need to do some more investigation. Nevertheless if you notice any issues let me know.

**Comment by opsNote5** [comment]
Hi @fakemanoan 

I have tested various features. Thank you for making this.
What is great, WiFi tethering is now allowed while on WiFi. This plus LineagesOS' VPN sharing makes super shine this device.
Only sad things (for me) was that I cannot fully relying on this phone, because I cannot connect my favorite WiFi network with the phone.

Most testing pass, I have full list I have done below:
Two log files are sending separately. (The fail scenarios)

Tested Phone: SM-N920W8

Installation (ISSUE, applied workaround mentioned above)
- lineage-18.1-20250408-UNOFFICIAL-noblelte 
- Upgrade, No GApps
		
Audio
- Audio playback for media content	Pass - (Built-in Recorder playback)
- Audio record	Pass - (Built-in Recorder)
- Phone in-call audio	Pass - (Built-in Phone)
- Phone speaker audio	Pass - (Built-in Phone)
- Bluetooth media audio-in(record)	Fail - (Buil-in Recorder app dies immediately after touching 'Record' Button)
- Bluetooth media audio-out	Pass - (Built-in Recorder, NewPipeApp)
- Bluetooth call audio-in/out	Pass - (Built-in Phone)
		
Text		
- Send	Pass - (Built-in 'Messaging' App)
- Receive	Pass - (Built-in 'Messaging' App)
- Image send (MMS)	Pass - (Built-in 'Messaging' App)
- Image receive (MMS)	Pass - (Built-in 'Messaging' App)
		
Wi-Fi		
- Connection - Normal	Pass
- Connection - One with issue	Fail - Still PROBLEM
				
Camera
- Rear (better quality)	Pass (Built-In 'Camera' App)
- Front (face)	Pass (Built-In 'Camera' App)

Video Recording
- Rear (better quality)	Pass (Built-In 'Camera' App, ??? - recorded audio volume is very low, could be some issue)
- Front (face)	Pass (Built-In 'Camera' App, ??? recorded audio volume is very low, could be some issue)

Other		
- Fingerprint	Pass (Able to unlock phone with fingerprint)
- GPS	Pass (OpenTopoMap)
- NFC	Pass (Use Free App 'NFC Reader', able to read some ID)
		
Tethering		
- WiFi	Pass (include while in WiFi - this is awesome)
- USB	Pass
- Bluetooth 	Pass
- Ethernet (via usb)	(Unable to test) Didn't recognize my USB-Ethernet adapter, may be my setup issue
- VPN share	Pass (WiFi Tethering, with Tai scale VPN, upstream WiFi)
- VPN share	Pass (Bluetooth tethering with Tailscale VPN, upstream WiFi)

(Non-Built-in) Apps		
- NewPipe	Pass
- Tailscale	Pass
- F-Droid	Pass

**Comment by fakemanoan** [comment]
The issue with WiFi is likely due to WPA3 being unsupported on our device. I thought setting WPA3 auto-upgrade to false would suffice, as it works on similar devices, however that doesn't seem to be the case, and the wifi hal still requests SAE. I only recently found this out because I got a new WPA3 capable router. Might be a kernel issue, will need to debug after I add bpf updates.

The bluetooth media recording is odd. I will look into it

**Comment by WeakFray** [comment]
@fakemanoan 
Just a quick update since I've been quite busy recently. I flashed the new ROM along with Gapps, and I didn't wipe the data partition. The phone isn't detecting my SIM card anymore, and it always says there's no SIM card inserted, so I can't test calls right now. I know this definitely wasn't an issue in the last build. However, I've noticed that after I put my SIM card in, it changes from "Emergency calls only" to "No service", so maybe it's just not registering properly? The weird thing is that my old SIM was recognized with no issues, carrier name and everything. Other SIM cards I had lying around show the same symptoms as my current SIM.

Everything else I've tested seems to be okay so far, no other issues have shown up yet. I'll write a full update on my testing later.

Logcats:
[logcat_20250418_1310_OldSIM.log](https://github.com/user-attachments/files/19815587/logcat_20250418_1310_OldSIM.log)
[logcat_20250418_1314_CurrentSIM.log](https://github.com/user-attachments/files/19815586/logcat_20250418_1314_CurrentSIM.log)

**Comment by oliviergareau** [comment]
Hello @fakemanoan 

I have decided to try your latest test build (18.1 20250408) without Gapps. I only tested for a couple of minutes because I was unable to connect to WiFi. My AP is a UniFi device running in WPA3/WPA2 mode. Also, I was unable to register my fingerprints: I get to the step where it asks to touch the sensor and nothing seems to happen when I do.


Recovery: Your TWRP build

Device: G920W8 (Galaxy S6 Canada version)

Thank you for the awesome work.

[lineage-18.1-20250408-UNOFFICIAL-zeroflte-fingerprint.log](https://github.com/user-attachments/files/19902589/lineage-18.1-20250408-UNOFFICIAL-zeroflte-fingerprint.log)

**Comment by fakemanoan** [comment]
Hi
Fingerprint issue will be solved in the next release, was a simple SELinux problem
I think I have working WPA3 downgrade working too. Expect a release in the next week. Thanks for the feedback!

**Comment by fakemanoan** [comment]
@oliviergareau these issues should be resolved in the newest test build.

https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A11-28042025

**Comment by oliviergareau** [comment]
Hi @fakemanoan ,

I just tested the new build and can confirm that the WiFi is fixed! 🥳 I also took some time to do further testing.

| Component | Status |
| --- | --- |
| WiFi with  WPA2/WPA3 AP | Works ✅ |
| Bluetooth | Works ✅ |
| 4G mobile data | Works ✅ |
| Wi-Fi hotspot | Works ✅ |
| NFC | Works ✅ |
| IR blaster | Works ✅ |
| Voice recorder & playback | Works ✅ |
| Fingerprint | Broken ❌ |
| Audio during mobile calls | Broken ❌ |

For the fingerprint reader, I get stuck at the same step where it asks to touch the sensor.

For this build, I decided to try inserting my SIM card in the phone. The mobile data worked after adjusting my APN settings. Calls DO work (I can send and receive calls and hear DTMF tones sent from my S6) but the speaker and microphone don't seem to work during the calls.

I created a logcat. Is there a way (email, signal, discord, etc) for me to send it directly to you? I rather send you the entire logs than redact sensitive information in them.

Thank you again for your continued efforts into this great phone. It is nice to breathe new life into it!

**Comment by fakemanoan** [comment]
You can send me a private message on XDA with a link to the file.

**Comment by fakemanoan** [comment]
Received logs, thanks. 

It appears I used the wrong macro for my SEPolicies (rw_dir_perms as opposed to create_dir_perms) which lacks a few permissions. That should be an easy fix.

The call audio is another thing. Considering it works on the note, and the fact that call audio worked before, that it is likely a kernel/dts issue. I will upload a temporary kernel for you to test later.

**Comment by fakemanoan** [comment]
[G920W8-28042025-test.zip](https://github.com/user-attachments/files/19948772/G920W8-28042025-test.zip)

@oliviergareau I have uploaded a test kernel with some changes. It does not use the unified dts, and instead uses the previous working configuration. Could you test this for me?

All you need to do is extract the zip, and transfer the .img to your phone. In TWRP you can select the image and flash it to "boot". Give call audio another attempt and let me know how it goes!

**Comment by oliviergareau** [comment]
@fakemanoan installed the kernel and tried a call. Still no audio (no microphone, no speaker) during calls.

Created a logcat and sent it via XDA in case you need it. 😄

**Comment by petquipue** [comment]
> [@fakemanoan](https://github.com/fakemanoan) installed the kernel and tried a call. Still no audio (no microphone, no speaker) during calls.

If you want audio during calls I would suggest you tried Fakemanoan's Lineage 19.1 version for NA Exynos. It sometimes take a couple of attemps before initate a call but at least it works. Just saying in case you did not know...

**Comment by fakemanoan** [comment]
My upcoming lineage 19 will also be based on this work, so moving to it will be a temporary fix. It is important to get this fixed properly.

XDA is currently down so I can't access the logs you sent me. But I am uploading another build with different audience firmware. We'll see if that works.

**Comment by WeakFray** [comment]
@fakemanoan

Hi again. I updated to the new build today and my SIM card is still not working in the phone, same problem in the last build. I temporarily reset my phone and reinstalled your February build of LineageOS 18.1 (20250211), and my SIM card worked in the older build. After I restored my backup with the latest build, the SIM card still didn't work. If you need other logs for this issue, let me know. I captured this one after the phone turned on and I put the SIM tray in.

**Logcats:**
[logcat_20250429_1208.log](https://github.com/user-attachments/files/19965520/logcat_20250429_1208.log)

**Comment by fakemanoan** [comment]
this seems to be related to cbd. odd that it doesnt work for your device. if i can't diagnose the issue i will just revert to the old prebuilt cbd.

**Comment by fakemanoan** [comment]
ok that sim detection issue is strange. i tried it on my own s6 edge and it also failed to detect a sim. i have no idea how this device worked on my previous roms considering the log output, but i think it is a kernel bug in the original samsung source code (whats new there >_>)

debugging it now, but i think i can fix it.

also received the logs. will look through it again.

**Comment by fakemanoan** [comment]
https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A11-01052025

try this release. @WeakFray 

let me know if anything is broken

**Comment by oliviergareau** [comment]
> https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A11-01052025
> 
> try this release. [@WeakFray](https://github.com/WeakFray) [@oliviergareau](https://github.com/oliviergareau)
> 
> let me know if anything is broken

Fingerprint works, call audio not working. Sending logcat via XDA.

**Comment by WeakFray** [comment]
@fakemanoan 
I installed the new release, and SIM detection still doesn't work. It still shows the same issues. I did the same procedure of turning the phone on then inserting the SIM tray.

**Logcats:**
[logcat_20250501_1216.log](https://github.com/user-attachments/files/20003548/logcat_20250501_1216.log)

**Comment by fakemanoan** [comment]
@WeakFray 
if you turn on the device then insert the sim it wont work, because the s6 doesnt have hotplug sim support. you need to insert the sim then turn on the device. it should work.

@oliviergareau 
it appears it is looking for a file path that does not exist. not sure why it wasnt complaining before. hopefully this will be the last update needed. sorry for all these builds lol.

**Comment by fakemanoan** [comment]
https://github.com/fakemanoan/bigtest/releases/download/test4/lineage-18.1-20250501-UNOFFICIAL-zeroflte-2.zip

try this one

**Comment by oliviergareau** [comment]
@fakemanoan 

You're a legend. Call audio now works!! 🎉🎉🎉

Uploaded logcat to XDA in case it could be useful.

Please let me know if there is anything else I can test or do to help out. Keeping old devices relevant and up-to-date is a noble cause.

**Comment by fakemanoan** [comment]
Good to hear it works. If you have any more issues then let me know. 

I will now add s6 edge+ to my list of todos, and then I will work on 19.1 and 20 unification too with bpf and all the other patches that needs once these builds are confirmed to be stable in avg usage.

**Comment by fakemanoan** [comment]
That issue should be resolved in an upcoming build. Hopefully.

**Comment by opsNote5** [comment]
@fakemanoan 

I have tested lineage-18.1-20250501-UNOFFICIAL-noblelte.zip
SM-N920W8 / Upgrade / No GApps

Installation now fixed (nobleltecan), so I can install the zip directly. Thank you.

Things STILL NOT working
- WIFI (in certain network)
- Bluetooth Audio (Specifically for recording, Playing works fine - My voice is not recorded in Recorder app (it automatically use phone's microphone), Phone call didn't deliver my voice to the destination, while using Bluetooth.

The fingerprint was broken in previous build 20250427, but I have confirmed 20250501 have also fixed.

Other things: I have noticed that to use fingerprint unlock, the phone needs to be active(screen on). If I remember correctly, previously fingerprint was working even if the phone screen was of.

Thank you for all your work

**Comment by fakemanoan** [comment]
@opsNote5 

Do you know if the WiFi was working prior in the initial builds?

The fingerprint didn't work with the screen off on the stock ROM, and having it always on would drain the battery like crazy from my experimentation, so this is not going to happen.

@WeakFray your issue of call audio should be resolved in the latest update i released yesterday.

**Comment by opsNote5** [comment]
@fakemanoan 
I do not know whether the WiFI was working before or not, but let me find it out.
Here is my plan:
1. I will first get the log file, and will send you.
2. re-flash back to the latest stock ROM (I assume that is what you mean, right?), then will test it, whether with stock ROM, it was working or not. 
It will probably take sometime, since it was my first time to flash back stock, and also I want to learn how to take backup - before flash back to the Stock.
Once I get the results, I will update you/here.

And thank you for the explanation for the fingerprint. And it make sense that fingerprint only work when phone is active to prevent battery drain, and follow stock ROM behavior. It is easy enough to press home button then unlock phone by the fingerprint, so we have no issue here.

**Comment by fakemanoan** [comment]
I was referring to the initial build I released for your device 

(this one: https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A11PRE-NAEXYNOSJAN25)

Was quite a while ago.  If it did work then that is very telling

**Comment by opsNote5** [comment]
@fakemanoan 
It didn't work from the beggining. So this issue continue:

I wrote earlier:
https://github.com/fakemanoan/LineageOS-Releases/issues/106#issuecomment-2585931824
> Critical issue (so far):
>     Unable to connect Public WiFi with Captive portal.
> 

And I'm talking about the same WiFi not working.

I have still plan to take a log file again, (unless you say no required), but it sounds I no longer need to re-flash, so I plan not to do.
Please let me know if you need more information.

**Comment by fakemanoan** [comment]
Ah my mistake, i must have scanned over that piece of info. I will let you know if I need any more info

**Comment by WeakFray** [comment]
@fakemanoan 
I installed the new release and I tested calls again. However, I still have the same issue of call audio not getting through to either end.

**Logcats:**
[logcat_20250505_1212.log](https://github.com/user-attachments/files/20041506/logcat_20250505_1212.log)

**Comment by fakemanoan** [comment]
Looking at the logs there are i2c errors. Checked and I may have mapped some pins wrong in the dts. 

I will release another build with this corrected. Again sorry for all the builds.

**Comment by fakemanoan** [comment]
@WeakFray 
https://github.com/fakemanoan/bigtest/releases/download/test5/lineage-18.1-20250506-UNOFFICIAL-zerolte.zip

try this

**Comment by fakemanoan** [comment]
Any luck?

**Comment by WeakFray** [comment]
@fakemanoan 
Sorry for the delay. I had the new build installed a few hours after you released it, but I was busy these past few days. I can confirm that call audio is now working properly. In addition, I was also able to connect the phone to my Wi-Fi network with dual WPA2/WPA3 security. Everything is working so far, but if there's any issues, I'll let you know.

**Comment by jcmtang** [comment]
The `lineage-18.1-20250507-UNOFFICIAL-noblelte` build seems to have noticeably more idle battery drain than `lineage-18.1-20250427-UNOFFICIAL-noblelte` on my `SM-N920W8`.

I can do a wipe and flash back to the the latest build (later this week) if you need logs.

**Comment by fakemanoan** [comment]
This can be for many reasons, but if you turned it on after and your battery % was 0, then likely your battery is degraded. Over time li-ion batteries cannot supply the same voltage at a given level. The BMS updates the capacity and sometimes it is 0, so your phone shuts down. If you have not replaced your battery before, this is the likely culprit.

I don't think this is a ROM issue, but if you take logs when it happens (adb is active in the boot anim as long as you have authorized keys) Ill have a look.
